version: 0.2
phases:
 install:
   commands:
     - echo "install step"
 pre_build:
   commands:
     - echo "pre_build step"
 build:
   commands:
     - npm run-script build
     - ls -l ./build
 post_build:
   commands:
     - echo "post_build step"